### ISSUE TITLE
re-produce the result on faces dataset

### ISSUE THREAD

**Issue by sangeet259** [sangeet259/Generative_Adversarial_Networks#4]
Generate new faces, yep those people don't exist !!!!!! :ghost:

**Comment by MJ10** [comment]
Can you post a link to the dataset please?

**Comment by sangeet259** [comment]
http://www.face-rec.org/databases/

**Comment by sangeet259** [comment]
There are various other datasets available for facial images I am not referring to a specific one'

**Comment by rootally** [comment]
#4 [Generated new faces with a comparison between GAN and DCGAN](https://github.com/rootally/Generating-new-faces-using-Gans)
