### ISSUE TITLE
implement style transfer using Generative Adversarial Networks

### ISSUE THREAD

**Issue by sangeet259** [sangeet259/Generative_Adversarial_Networks#6]

**Comment by suvojit-0x55aa** [comment]
Hi, Can I work on this for KWOC ?

**Comment by sangeet259** [comment]
@suvojit-0x55aa Sure Please join the slack channel for communication purposes 
https://join.slack.com/t/kwoc-17/shared_invite/enQtMjczNDI1OTY5NzE0LTljNzY3YzIzMGY3YzY5ODc1MGQyYjUyMzVkYjlmYTg1MTY4MWZhY2FhZjkwMWFiYjMzMjk1NjM5YTk1YTM1MmU
